const Portfolio_data = [
    {
      id: 1,
      category: "Cozinha",
      title: "Estilos modernos de cozinha ",
      content: "Cozinha moderna com armários superiores e luminárias pendentes com forno e cooktop, coifa e vale destacar a parede com ladrilhos.",
      image: "../../1.jpeg",
    },
    {
      id: 2,
      category: "Cozinha e copa",
      title: "Visão do reaproveitamento de espaço",
      content: "Com reaproveitamento do espaço para uma mesa pequena de jantar no canto com um lustre rústico. ",
      image: "../../2.jpeg",
    },
    {
      id: 3,
      category: "visão geral do interior",
      title: "Designer de salas,cozinha e copa ",
      content: "Designer ideal para apartamentos e casas pequenas, onde ocupamos todo o espaço com charme e leveza.",
      image: "../../3.jpeg",
    },
    {
      id: 4,
      category: "Espaço gourmet",
      title: "Churrasqueira e espaço para confraternizações ",
      content: "Espaço coberto com churrasqueira embutida e mesa, bom destacar o vidro com visão total do interior da casa.",
      image: "../../4.jpeg",
    },
    {
      id: 5,
      category: "Lavanderia",
      title: "Aproveitamento do espaço para lavanderia ",
      content: "Com pouco espaço criamos uma lavanderia com uma máquina lava e seca, pia e armário para útensilios domésticos, com um vitrô para ventilação.",
      image: "../../5.jpeg",
    },
    {
      id: 6,
      category: "Escola",
      title: "Projeto escolar ",
      content: "Visão frontal do projeto escolar",
      image: "../../6.png",
    },
    {
      id: 7,
      category: "Escola",
      title: "Projeto escolar ",
      content: "Visão traseira do projeto escolar",
      image: "../../7.png",
    },
    {
      id: 8,
      category: "Residencial",
      title: "Planta residencial ",
      content: "Planta baixa com as medidas, ferramenta utilizada AutoCad",
      image: "../../8.png",
    },
    {
      id: 8,
      category: "Fachada",
      title: "Mudança na fachada ",
      content: "Realizei a alteração da fachada antiga para esta, com telhado embutido e garagem aberta, estilos casas americanas e gramado frontal",
      image: "../../9.png",
    },
]
export default Portfolio_data