const Portfolio_data = [
    {
      id: 1,
      category: "Cozinha",
      title: "Estilos modernos de cozinha ",
      content: "Cozinha moderna com armários superiores e luminárias pendentes com forno e cooktop, coifa e vale destacar a parede com ladrilhos.",
      image: "../../1.jpeg",
    },
    {
      id: 2,
      category: "Cozinha e copa",
      title: "Visão do reaproveitamento de espaço",
      content: "Com reaproveitamento do espaço para uma mesa pequena de jantar no canto com um lustre rústico. ",
      image: "../../2.jpeg",
    },
    {
      id: 3,
      category: "visão geral do interior",
      title: "Designer de salas,cozinha e copa ",
      content: "Designer ideal para apartamentos e casas pequenas, onde ocupamos todo o espaço com charme e leveza.",
      image: "../../3.jpeg",
    },
    {
      id: 4,
      category: "Espaço gourmet",
      title: "Churrasqueira e espaço para confraternizações ",
      content: "Espaço coberto com churrasqueira embutida e mesa, bom destacar o vidro com visão total do interior da casa.",
      image: "../../4.jpeg",
    },
    {
      id: 5,
      category: "Chácara",
      title: "Visões laterais e interna ",
      content: "Projeto recém concluído com espaço amplo para acomodações e descanso.",
      image: "../../10.jpg",
    },
    {
      id: 6,
      category: "Medidas",
      title: "Chácara São João Batista ",
      content: "Visão frontal do projeto escolar",
      image: "../../11.jpg",
    },
    {
      id: 7,
      category: "Escola",
      title: "Projeto escolar ",
      content: "Visão traseira do projeto escolar",
      image: "../../7.png",
    },
    {
      id: 8,
      category: "Medidas",
      title: "Visão geral visto de cima ",
      content: "Visão de como irá ficar os móveis e eletrodomésticos, para assim casar todas as coisas, deixando o ambiente compátivel com seu gosto.",
      image: "../../12.jpg",
    },
    {
      id: 8,
      category: "Interior",
      title: "Mudança radical do interior ",
      content: "Com o pouco espaço, precisei alterar os móveis e TV de local, sendo assim, repaginei o ambiente aproveitando para colocar papel de parede e quadros para deixar um ambiente mais familiar.",
      image: "../../13.jpg",
    },
]
export default Portfolio_data